   name: Publish NuGet Package

   on:
     push:
       branches:
         - master
     pull_request:
       branches:
         - master

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up .NET
           uses: actions/setup-dotnet@v2
           with:
             dotnet-version: '6.x'

         - name: Restore dependencies
           run: dotnet restore

         - name: Build the project
           run: dotnet build --configuration Release --no-restore

         - name: Pack the project
           run: dotnet pack --configuration Release --no-build --output ./nupkg

         - name: Publish NuGet package
           env:
             NUGET_API_KEY: ${{ secrets.NUGET }}
           run: dotnet nuget push ./nupkg/*.nupkg -k $NUGET -s https://api.nuget.org/v3/index.json
