version: '3.4'

networks:
  webapi:
    driver: bridge

services:
  sample:
    container_name: "sample-api"
    image: ${DOCKER_REGISTRY-}sample
    build:
      context: .
      dockerfile: sample/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - "webapi"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - elasticsearch
 
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.2
    ports:
      - 9200:9200
    networks:
      - "webapi"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:8.12.2
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - "webapi"
    depends_on:
      - elasticsearch


volumes:
  elasticsearch-data:
