name: Publish NuGet Package

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.*

    - name: Restore dependencies
      run: dotnet restore LoggerEnhancer/LoggerEnhancer.csproj

    - name: Build the project
      run: dotnet build LoggerEnhancer/LoggerEnhancer.csproj --configuration Release --no-restore

    - name: Pack the project
      run: dotnet pack LoggerEnhancer/LoggerEnhancer.csproj --configuration Release --no-build --output ./nupkg

    - name: Publish NuGet package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET }}
      run: dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
