name: Run tests

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.*

    - name: Restore dependencies
      run: dotnet restore tests/tests.csproj

    - name: Run tests
      run: dotnet test tests/tests.csproj --logger trx --results-directory TestResults
